### ISSUE TITLE
Issues with pkgdown site

### ISSUE THREAD

**Issue by EHJ-52n** [52North/sos4R#104]
## Description

The current test version of the new documentation page is available via:

 - https://nuest.github.io/sos4R/

and the final version should be available via

- https://52north.github.io/sos4R/

## Problems

- [x] Spacing between top navigation and content must be fixed. ![sos4r-website_spacing-issue](https://user-images.githubusercontent.com/3839896/53563063-448e1f80-3b53-11e9-98f3-5498333e82b8.png)

**Comment by nuest** [comment]
Seems to be fixed!

![image](https://user-images.githubusercontent.com/1325054/64517463-b01a2c00-d2f0-11e9-8555-e571345fb4e2.png)

![image](https://user-images.githubusercontent.com/1325054/64517492-bc9e8480-d2f0-11e9-8f98-b6dd24c6cf72.png)
