### ISSUE TITLE
Change release version tags to "vx.y.z" format

### ISSUE THREAD

**Issue by EHJ-52n** [52North/sos4R#105]
The tags for releases MUST follow the format "vx.y.z", hence the listing and logic of our orga download page works:

https://52north.github.io/

**Comment by nuest** [comment]
@EHJ-52n This just requires update of the documentation, correct?

**Comment by EHJ-52n** [comment]
At least updating the one and only tag of the project so far: [0.2-11](https://github.com/52North/sos4R/tree/0.2-11)..

I could not find any documentation for releasing and tagging, so feel free to add some.

**Comment by nuest** [comment]
Docs included in https://github.com/nuest/sos4R/commit/c7dd63fcc32b95a065bdd4864f2219c6667ca747

Tag is updated.
