### ISSUE TITLE
Switch from SosAllNamespaces() to SosAllNamespaces(sos@version)

### ISSUE THREAD

**Issue by EHJ-52n** [52North/sos4R#132]
We should replace `SosAllNamespaces()` with `SosAllNamespaces(sos@version)¸, otherwise the SOSv1.0-NS will unexpectedly be set and we will be less generic. 
This change requires test adjustment because Test_SOS (..) supplies a 1.0-SOS instance.

**Comment by nuest** [comment]
Further suggestion: let's store the namespaces with the SOS object, `sos@namespaces`, so a) users can manipulate namespaces if they need to, and b) we can use the namespace in parsing functions where `sos` is already passed as a function/method parameter.
