### ISSUE TITLE
Add support for SWE 2.0 DataArray

### ISSUE THREAD

**Issue by nuest** [52North/sos4R#138]
See https://github.com/nuest/sos4R/commit/9a4d43322fe89594c8450df194cbd8af818f3aad 

Blocks #96

**Comment by EHJ-52n** [comment]
Fixed by [ehj-52n@2c1696db](https://github.com/EHJ-52n/sos4R/commit/2c1696db20104be9f77a02f79db9e3e5faf241f1)
