### ISSUE TITLE
Evaluate mocking for tests

### ISSUE THREAD

**Issue by nuest** [52North/sos4R#78]
https://github.com/ropensci/webmockr, depdends on #77

Can we simply map a request to an XML file on the disk?

**Comment by EHJ-52n** [comment]
@nuest Yes, we can! See [EHJ-52n/sos4R:feature/4.0:tests/testthat/test_phenomena.R#L69](https://github.com/EHJ-52n/sos4R/blob/681f1e94e038e55ff1ad8db15b20f0f72b1a0524/tests/testthat/test_phenomena.R#L69)

**Comment by nuest** [comment]
Nice!
