### ISSUE TITLE
List all sites with metadata: only phenomena

### ISSUE THREAD

**Issue by EHJ-52n** [52North/sos4R#92]
## R implementation 

```R
sites(sos, empty = FALSE, includePhenomena = TRUE, includeTemporalBBox = FALSE)
→
sp::SPDF[siteID, phen_1=logical, …, phen_n=logical]
```

## Used SOS operations/requests

* GetDataAvailability v1.0
* GetFeatureOfInterest w/feature list

## Related Issues

* #90 
* #91 
* #93

**Comment by EHJ-52n** [comment]
This is blocked by https://github.com/52North/sos4R/issues/122 atm.

**Comment by EHJ-52n** [comment]
Re-check with NIWA SOS.

**Comment by nuest** [comment]
Vignette error:

![image](https://user-images.githubusercontent.com/1325054/57923239-0840a480-78a2-11e9-8a46-d884a262f3e7.png)

------

https://hydro-sos.niwa.co.nz/?version=2.0.0&service=SOS&request=GetDataAvailability&observedProperty=pH

https://hydro-sos.niwa.co.nz/?version=2.0.0&service=SOS&request=GetDataAvailability&featureOfInterest=DN5

**Comment by EHJ-52n** [comment]
Already solved: https://ehj-52n.github.io/sos4R/articles/sos4R-vignette-05-wrapper-functions.html#sites
