### ISSUE TITLE
Retrieve sensor values by phenomenon/a and single site/list of sites

### ISSUE THREAD

**Issue by EHJ-52n** [52North/sos4R#96]
## R implementation 

* `getData(sos, phenomena=[Vector/one-column df of phenomena], sites=[Vector/one-column df of sites]) → data.frame[siteID, timestamp, phen_1, phen_2, …]`
  * Use Units package! See #47 

## Used SOS operations/requests
* GetObservation (w/ list of phenomena and list of sites)

## Related Issues

* #98 
* #100

**Comment by nuest** [comment]
Must also handle multiple types - cannot use `sosResult(..)`:

```
> getData(sos = niwaHydro,
+         phenomena = phenomena$phenomenon[1:2],
+         sites = siteList$siteID[1],
+         retrieveFOI = FALSE, # TO BE FIXED
+         )
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
```

**Comment by EHJ-52n** [comment]
@BenGraeler it is working but not using the unit package and some metadata is lost during the column merge. I switched to dplyr but not all column data is preserved.

Please review if the in [test_getData.R::294](https://github.com/52North/sos4R/blob/feature/0.4/tests/testthat/test_getData.R#L294) is enough for this issue to be closed. Re-open, if not.
